# This file may not be shared/redistributed without permission. Please read copyright notice in the git repo. If this file contains other copyright notices disregard this text.
"""
This project resembles the Inventory-control problem discussed in (Her25, Subsection 5.1.2) but with more complicated rules.
If you are stuck, the inventory-control problem will be a good place to start.

I recommend to use the DP_stochastic function (as we did with the inventory-control example). This means
your main problem is to build appropriate DPModel-classes to represent the different problems.

References:
  [Her25] Tue Herlau. Sequential decision making. (Freely available online), 2025.
"""
from irlc.ex02.dp_model import DPModel
from irlc.ex02.dp import DP_stochastic
import matplotlib.pyplot as plt
from scipy.stats import binom
from irlc import savepdf
import numpy as np

# Problem 2:
def warmup_states():
    return set(range(21)) #S_k = {0,1,...,20}, for k = 0,...,N

def warmup_actions():
    return set(range(16)) # A_k(x_k) = {0,1,...,15}, for k = 0,...,N-1

def plot_policy(pi, title, pdf):
    """ Helper function to plot the policy functions pi, as generated by the DP_stochastic function. This function
    can be used to visualize which actions are taken in which state (y-axis) at which time step (x-axis). """
    N = len(pi)
    W = max(pi[0].keys())
    A = np.zeros((W, N))
    for i in range(W):
        for j in range(N):
            A[i, j] = pi[j][i]
    plt.imshow(A)
    plt.title(title)
    savepdf(pdf)
    plt.show()

NS = 20          
NO = 15          
CO = 1.5         
SP = 2.1         
N_HORIZON = 14   
P_BINOM = 1/5    
DISPOSAL_COST = 3.0


class Kiosk1DP(DPModel):
    """DP model for Kiosk 1 (disposal is free, demand is {0,3,6} with fixed probs)."""

    def __init__(self):
        super().__init__(N=N_HORIZON)

    def S(self, k):
        return range(NS + 1)

    def A(self, x, k):
        return range(NO + 1)

    def Pw(self, x, u, k):
        # Demand distribution for Kiosk1
        return {0: 0.3, 3: 0.6, 6: 0.1}

    def f(self, x, u, w, k):
        # Sell min(x+u, w), leftover cannot be negative, storage capped at NS (free disposal)
        sold = min(x + u, w)
        leftover = (x + u) - sold
        leftover = max(0, leftover)
        return min(NS, leftover)

    def g(self, x, u, w, k):
        # Cost = ordering cost - revenue (DP minimizes cost)
        sold = min(x + u, w)
        return CO * u - SP * sold

    def gN(self, x):
        return 0.0


class Kiosk2DP(DPModel):
    """DP model for Kiosk 2 (binomial demand + disposal cost)."""

    def __init__(self):
        super().__init__(N=N_HORIZON)

    def S(self, k):
        return range(NS + 1)

    def A(self, x, k):
        return range(NO + 1)

    def Pw(self, x, u, k):
        # Full binomial distribution over w=0..NS
        # Using scipy.stats.binom imported at top of file
        pmf = binom.pmf(np.arange(NS + 1), NS, P_BINOM)
        return {w: float(pmf[w]) for w in range(NS + 1)}

    def f(self, x, u, w, k):
        sold = min(x + u, w)
        leftover = (x + u) - sold
        leftover = max(0, leftover)

        # storage cap NS, excess is discarded (but now costs money in g)
        return min(NS, leftover)

    def g(self, x, u, w, k):
        sold = min(x + u, w)
        leftover = (x + u) - sold
        leftover = max(0, leftover)

        excess = max(0, leftover - NS)
        return CO * u - SP * sold + DISPOSAL_COST * excess

    def gN(self, x):
        return 0.0


def warmup_states():
    # S0 = {0,1,...,20}
    return set(range(NS + 1))


def warmup_actions():
    # A(x0) = {0,1,...,15} (independent of x0)
    return set(range(NO + 1))


def solve_kiosk_1():
    model = Kiosk1DP()
    J, pi = DP_stochastic(model)
    return J, pi


def solve_kiosk_2():
    model = Kiosk2DP()
    J, pi = DP_stochastic(model)
    return J, pi

def warmup_states():
    return list(range(21))  # or set(range(21))

def warmup_actions():
    return list(range(16))  # or set(range(16))

def solve_kiosk_1():
    model = Kiosk1DP()
    J, pi = DP_stochastic(model)
    return J, pi

def solve_kiosk_2():
    model = Kiosk2DP()
    J, pi = DP_stochastic(model)
    return J, pi


def main():
    # Problem 14
    print("Available states S_0:", warmup_states())
    print("Available actions A_0(x_0):", warmup_actions())

    J, pi = solve_kiosk_1() # Problem 16
    print("Kiosk1: Expected profits: ", -J[0][0], " imperial credits")
    plot_policy(pi, "Kiosk1", "Latex/figures/kiosk1")
    plt.show()

    J, pi = solve_kiosk_2() # Problem 17
    print("Kiosk 2: Expected profits: ", -J[0][0], " imperial credits")
    plot_policy(pi, "Kiosk2", "Latex/figures/kiosk2")
    plt.show()


if __name__ == "__main__":
    main()
